/*
AUTORES - ESTUDIANTES
 JHONATAN ADALID (320368)
 LORENZO ALDAO (307239)
*/
package obligatorio2parking;

import dominio.*;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class VentanaContratos extends javax.swing.JFrame implements Observer{
    private Sistema sistema;

    public VentanaContratos(Sistema sistema) {
        this.sistema = sistema;
        this.sistema.addObserver(this);
        initComponents();
        cargarDatosIniciales();
        txtAreaContratos.setEditable(false);
    }
    
    public VentanaContratos() {
        initComponents();
        txtAreaContratos.setEditable(false);
    }
    
    private void cargarDatosIniciales() {
        cargarComboVehiculos();
        cargarComboClientes();
        cargarComboEmpleados();
        cargarListaContratos();
    }
    
    private void cargarComboVehiculos() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Vehiculo v : sistema.getVehiculos()) {
            model.addElement(v.toString());
        }
        comboVehiculos.setModel(model);
    }
    
    private void cargarComboClientes() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Cliente c : sistema.getClientes()) {
            model.addElement(c.toString());
        }
        comboClientes.setModel(model);
    }
    
    private void cargarComboEmpleados() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Empleado emp : sistema.getEmpleados()) {
            System.out.println(sistema.getEmpleados());
            model.addElement(emp.toString());
        }
        comboEmpleados.setModel(model);
    }
    
    private void cargarListaContratos() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Contrato cont : sistema.getContratos()) {
            model.addElement(cont.toString());
        }
        listaContratos.setModel(model);
    }
    
    
    private void mostrarDetalleContrato() {
        int idx = listaContratos.getSelectedIndex();
        if (idx == -1) {
            txtAreaContratos.setText("Seleccione un contrato.");
            return;
        }
        Contrato contrato = sistema.getContratos().get(idx);
        txtAreaContratos.setText(contrato.mostrarDetalle());
    }
    
@Override
public void update(Observable o, Object arg) {
    cargarDatosIniciales();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVehiculosContratos = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        comboVehiculos = new javax.swing.JComboBox<>();
        comboClientes = new javax.swing.JComboBox<>();
        comboEmpleados = new javax.swing.JComboBox<>();
        lblEmpleado = new javax.swing.JLabel();
        lblValorMensual = new javax.swing.JLabel();
        txtValorMensual = new javax.swing.JTextField();
        btnAgregarContrato = new javax.swing.JButton();
        scrollContratos = new javax.swing.JScrollPane();
        listaContratos = new javax.swing.JList<>();
        lblContratos = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();
        btnMostrarDetalle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaContratos = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contratos");

        lblVehiculosContratos.setText("Vehículos:");

        lblClientes.setText("Clientes:");

        comboVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVehiculosActionPerformed(evt);
            }
        });

        lblEmpleado.setText("Empleado:");

        lblValorMensual.setText("Valor Mensual:");

        txtValorMensual.setColumns(5);

        btnAgregarContrato.setText("Agregar");
        btnAgregarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContratoActionPerformed(evt);
            }
        });

        scrollContratos.setViewportView(listaContratos);

        lblContratos.setText("Contratos:");

        lblDetalles.setText("Detalles:");

        btnMostrarDetalle.setText("Mostrar Detalle");
        btnMostrarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDetalleActionPerformed(evt);
            }
        });

        txtAreaContratos.setColumns(20);
        txtAreaContratos.setRows(5);
        jScrollPane1.setViewportView(txtAreaContratos);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(lblContratos)
                        .addGap(148, 148, 148)
                        .addComponent(lblDetalles))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehiculosContratos)
                            .addComponent(comboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpleado)
                            .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClientes)
                            .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorMensual)
                            .addComponent(txtValorMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(scrollContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnAgregarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEliminar)
                        .addGap(67, 67, 67)
                        .addComponent(btnMostrarDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContratos)
                    .addComponent(lblDetalles))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVehiculosContratos)
                                .addGap(4, 4, 4)
                                .addComponent(comboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblEmpleado)
                                .addGap(14, 14, 14)
                                .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClientes)
                                .addGap(4, 4, 4)
                                .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblValorMensual)
                                .addGap(14, 14, 14)
                                .addComponent(txtValorMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarContrato)
                    .addComponent(btnEliminar)
                    .addComponent(btnMostrarDetalle))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setBounds(0, 0, 806, 311);
    }// </editor-fold>//GEN-END:initComponents

    private void comboVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVehiculosActionPerformed

    private void btnAgregarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContratoActionPerformed
        try {
            int idxVehiculo = comboVehiculos.getSelectedIndex();
            int idxCliente = comboClientes.getSelectedIndex();
            int idxEmpleado = comboEmpleados.getSelectedIndex();
            double valorMensual = Double.parseDouble(txtValorMensual.getText());

            if (idxVehiculo == -1 || idxCliente == -1 || idxEmpleado == -1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar vehículo, cliente y empleado");
                return;
            }

            Vehiculo vehiculo = sistema.getVehiculos().get(idxVehiculo);
            Cliente cliente = sistema.getClientes().get(idxCliente);
            Empleado empleado = sistema.getEmpleados().get(idxEmpleado);

            boolean agregado = sistema.agregarContrato(vehiculo, cliente, empleado, valorMensual);
            if (agregado) {
                JOptionPane.showMessageDialog(this, "Contrato agregado correctamente");
                txtValorMensual.setText("");
                sistema.notifyObservers(); // Forzar actualización
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar contrato");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor mensual válido");
        }
    }//GEN-LAST:event_btnAgregarContratoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDetalleActionPerformed
        mostrarDetalleContrato();
    }//GEN-LAST:event_btnMostrarDetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaContratos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarContrato;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrarDetalle;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JComboBox<String> comboEmpleados;
    private javax.swing.JComboBox<String> comboVehiculos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblContratos;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblValorMensual;
    private javax.swing.JLabel lblVehiculosContratos;
    private javax.swing.JList<String> listaContratos;
    private javax.swing.JScrollPane scrollContratos;
    private javax.swing.JTextArea txtAreaContratos;
    private javax.swing.JTextField txtValorMensual;
    // End of variables declaration//GEN-END:variables
}
