/*
AUTORES - ESTUDIANTES
 JHONATAN ADALID (320368)
 LORENZO ALDAO (307239)
*/
package obligatorio2parking;

import dominio.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class VentanaEntradas extends javax.swing.JFrame implements Observer {
    private Sistema sistema;
    
    public VentanaEntradas(Sistema sistema){
        this.sistema = sistema;
        this.sistema.addObserver(this);
        initComponents();
        cargarDatosIniciales();
        configurarSpinners();
    }
    
    private void cargarDatosIniciales() {
        cargarComboVehiculos();
        cargarComboEmpleados();
    }
    
    private void cargarComboVehiculos() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Vehiculo v : sistema.getVehiculos()) {
            model.addElement(v.toString());
        }
        comboVehiculos.setModel(model);
    }
     
    private void cargarComboEmpleados() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Empleado emp : sistema.getEmpleados()) {
            System.out.println(sistema.getEmpleados());
            model.addElement(emp.toString());
        }
        comboEmpleados.setModel(model);
    }
    
    private Vehiculo obtenerVehiculoPorIndice(int index) {
    int contador = 0;
    for (Vehiculo v : sistema.getVehiculos()) {
        if (!sistema.vehiculoEstaEnParking(v)) {
            if (contador == index) {
                return v;
            }
            contador++;
        }
    }
    return null;
    }
    
    private void configurarSpinners() {
        // Configurar spinner de fecha/hora
        spinFechaHora.setModel(new javax.swing.SpinnerDateModel());
        spinFechaHora.setEditor(new javax.swing.JSpinner.DateEditor(spinFechaHora, "dd/MM/yyyy HH:mm"));
        spinFechaHora.setValue(new Date());
    }
    
    private void limpiarFormulario() {
        txtAreaNotas.setText("");
        spinFechaHora.setValue(new Date());
        if (comboVehiculos.getItemCount() > 0) {
            comboVehiculos.setSelectedIndex(0);
        }
        if (comboEmpleados.getItemCount() > 0) {
            comboEmpleados.setSelectedIndex(0);
        }
        lblContrato.setText("Contrato:");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        comboVehiculos = new javax.swing.JComboBox<>();
        lblVehiculo = new javax.swing.JLabel();
        spinFechaHora = new javax.swing.JSpinner();
        lblFechaHora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaNotas = new javax.swing.JTextArea();
        lblNotas = new javax.swing.JLabel();
        comboEmpleados = new javax.swing.JComboBox<>();
        lblEmpleado = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        lblContrato = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entradas");
        getContentPane().setLayout(null);

        comboVehiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVehiculosActionPerformed(evt);
            }
        });

        lblVehiculo.setText("Vehiculo");

        lblFechaHora.setText("Fecha y hora");

        txtAreaNotas.setColumns(20);
        txtAreaNotas.setRows(5);
        jScrollPane1.setViewportView(txtAreaNotas);

        lblNotas.setText("Notas");

        comboEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmpleadosActionPerformed(evt);
            }
        });

        lblEmpleado.setText("Empleado ");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblContrato.setText("Contrato:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboVehiculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVehiculo)
                        .addComponent(spinFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFechaHora)
                    .addComponent(lblNotas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpleado)
                    .addComponent(lblContrato)
                    .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo)
                    .addComponent(lblEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblFechaHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContrato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnConfirmar)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 480, 300);

        setBounds(0, 0, 490, 308);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
         // Obtener los índices seleccionados
            int vehiculoIndex = comboVehiculos.getSelectedIndex();
            int empleadoIndex = comboEmpleados.getSelectedIndex();

            if (vehiculoIndex == -1 || empleadoIndex == -1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un vehículo y un empleado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Obtener los objetos reales usando los índices
            Vehiculo vehiculoSeleccionado = obtenerVehiculoPorIndice(vehiculoIndex);
            Empleado empleadoSeleccionado = sistema.getEmpleados().get(empleadoIndex);

            Date fechaHora = (Date) spinFechaHora.getValue();
            String nota = txtAreaNotas.getText().trim();

            if (vehiculoSeleccionado == null || empleadoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Error al obtener vehículo o empleado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Formateo fecha y hora
            DateTimeFormatter formatterFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DateTimeFormatter formatterHora = DateTimeFormatter.ofPattern("HH:mm");
            LocalDateTime fechaHoraLocal = LocalDateTime.ofInstant(fechaHora.toInstant(), java.time.ZoneId.systemDefault());

            String fecha = fechaHoraLocal.format(formatterFecha);
            String hora = fechaHoraLocal.format(formatterHora);

            // Agregar la entrada
            boolean registrada = sistema.agregarEntrada(vehiculoSeleccionado, fecha, hora, nota, empleadoSeleccionado);
            if (registrada) {
                JOptionPane.showMessageDialog(this, "Entrada registrada exitosamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                txtAreaNotas.setText(""); // Limpiar nota
                spinFechaHora.setValue(new Date()); // Resetear fecha/hora a ahora
            } else {
                JOptionPane.showMessageDialog(this, "El vehículo ya está dentro del parking.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void comboVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVehiculosActionPerformed
            Vehiculo vehiculoSeleccionado = (Vehiculo) comboVehiculos.getSelectedItem();
        if (vehiculoSeleccionado != null) {
            Contrato contrato = sistema.buscarContratoPorVehiculo(vehiculoSeleccionado);
            if (contrato != null) {
                lblContrato.setText("Contrato: SÍ - Cliente: " + contrato.getCliente().getNombre());
            } else {
                lblContrato.setText("Contrato: NO");
            }
        } else {
            lblContrato.setText("Contrato:");
        }
    }//GEN-LAST:event_comboVehiculosActionPerformed

    private void comboEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpleadosActionPerformed
        
    }//GEN-LAST:event_comboEmpleadosActionPerformed

    @Override
    public void update(Observable o, Object arg) {
        cargarDatosIniciales();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sistema sistema = new Sistema();
                new VentanaEntradas(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> comboEmpleados;
    private javax.swing.JComboBox<String> comboVehiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JSpinner spinFechaHora;
    private javax.swing.JTextArea txtAreaNotas;
    // End of variables declaration//GEN-END:variables
}
